version: "3.2"
services:
  nodejs:
    build: 
      context: .
    image: sudhakar1/node-web-app
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=sudha-mysql-app
      - MYSQL_USER=sudhauser
      - MYSQL_PASS=sudhapass
      - MYSQL_DB=sudha_db
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:8005"
    container_name: sudha-nodejs-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=sudhauser
      - MYSQL_PASSWORD=sudhapass 
      - MYSQL_DATABASE=sudha_db
    container_name: sudha-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=sudha-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: sudha-phpmyadmin-app
networks:
  frontend:
  backend: