version: "3.2"
services:
  nodejs:
    build: 
      context: .
    image: lmpsureify/node-web-app
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=lmp-mysql-app
      - MYSQL_USER=lmpuser
      - MYSQL_PASS=lmppass
      - MYSQL_DB=lmp_db
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:8005"
    container_name: lmp-nodejs-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=lmpuser
      - MYSQL_PASSWORD=lmppass 
      - MYSQL_DATABASE=lmp_db
    container_name: lmp-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=lmp-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: lmp-phpmyadmin-app
networks:
  frontend:
  backend: